server:
  port: 8010
#指定当前服务名称
spring:
  application:
    name: MyCustomer
#指定eureka服务的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
debug: false
